### ISSUE TITLE
Implement glucose data backfills

### ISSUE THREAD

**Issue by efidoman** [xdrip-js/xdrip-js#21]
Implement backfill for when the rig isn't near the transmitter, and backfill for when the rig isn't uploading to NS.

When you ask the transmitter for backfill data you get a long list of messages like this:
```
0180f93e00009e32660057000602ca3366005c00
02800606f63466005f000608223666006600060a
03804e376600640006067a38660063000603a639
0480660063000600d23a6600610006fefe3b6600
0580610006fe2a3d6600610006ff563e66006100
06800600823f66005d0006feae406600570006fa
0780da416600550007f906436600580007fc3244
088066005b0007025e456600630007088a466600
09806b00070db64766007200070fe24866007400
0a80070c0e4a6600880006073a4b660090000608
0b80664c66008e000604924d660089000600be4e
0c8066007f0006f8ea4f6600790006f316516600
0d80700006f1425266006f0006f56e5366006d00
0e8006f99a546600660006f9c6556600650006fa
0f80f2566600680006fd1e586600700006044a59
1080660070000606765a66006e000603a25b6600
1180680006fdce5c6600690006fc
```
each message starts with a counter (01, 02) and the byte 0x80 and then the payload, which is a repeating sequence of [timestamp (4 bytes), glucose (2 bytes), status (1 byte), trend (1 byte)]
A parser would accept these incoming messages and spit out glucose events.

xdrip+ has backfill today.
iosxdrip does not.

**Comment by thebookins** [comment]
Ideally, we should use the above capture as a text fixture and write a test case to ensure that the parser does it's job properly.

**Comment by delahere** [comment]
I'm having a little bit of trouble following. From the explanation and the first two lines of the data above, is this the idea?
01 Sequence number
80 Message type?
f93e0000  Timestamp?
9e32  glucose?
66 status?
00 trend?
57000602ca3366005c00 ???

02 Sequence number
80 Message type?
0606f634  Timestamp?
6600 glucose?
5f  status?
00  trend?
0608223666006600060a ???

**Comment by efidoman** [comment]
This issue should be closed now since @alimhassam did the work already in xdrip-js to implement tx backfill.

**Comment by jpcunningh** [comment]
closing issue, thanks to @alimhassam for implementing backfill!
